name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch: # allow manual runs

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: ./README.md
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Colombo

          # Plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_followup: yes
          plugin_repositories: yes
